name: flutter_local_authentication
description: "A flutter plugin that allows access to Local Authentication / Biometrics on iOS, macOS, Linux and Android."
version: 1.0.0
homepage: "https://eaceto.dev"
repository: "https://github.com/eaceto/flutter_local_authentication/"

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.eaceto.mobile.oss.flutter.flutter_local_authentication
        pluginClass: FlutterLocalAuthenticationPlugin
      ios:
        pluginClass: FlutterLocalAuthenticationPlugin
      linux:
        pluginClass: FlutterLocalAuthenticationPlugin
      macos:
        pluginClass: FlutterLocalAuthenticationPlugin
      windows:
        pluginClass: FlutterLocalAuthenticationPluginCApi
